---

version: "3.7"

services:

  nginx:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    image: "nginx:${NGINX_VERSION}"
    container_name: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}:cached
      - ./config/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
      - mariadb

  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    image: "php-fpm:${PHP_VERSION}"
    container_name: php
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}:cached
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mariadb

  node:
    build:
      context: ./config/node
      dockerfile: Dockerfile
    image: node:${NODE_VERSION}
    container_name: node
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}:cached

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    restart: always
    volumes:
      - nginx_db_data:/var/lib/mysql:cached
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_NAME}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

volumes:
    nginx_db_data:
